services:
    # Reverse proxy for the frontend and other services
    nginx-ssl:
        build:
            context: ./dev/nginx/
        ports:
            - "80:80"
            - "443:443"
        environment:
            - ACCOUNT_SERVICE=http://host.docker.internal:8080
            - FRONTEND_SERVICE=http://host.docker.internal:8085
            - FILE_SERVICE=http://localhost
            - DOCUMENT_SERVICE=http://localhost
        networks:
            - nginx-net

    # Account service
    keydb-state:
        image: bitnami/keydb:6.3.4
        ports:
            - 6379:6379
        environment:
            - KEYDB_DATABASE=state
            - KEYDB_PASSWORD=1234

    accounts-db:
        image: postgres:17.2
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=accounts
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234
        volumes:
            - accounts-db:/var/lib/postgresql/data
            - ./dev/db/accounts/init:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    accounts-db:

networks:
    nginx-net:
        driver: bridge