services:
    # Reverse proxy for the frontend and other services
    nginx-ssl:
        build:
            context: ./dev/nginx/
        restart: always
        ports:
            - "80:80"
            - "443:443"
        environment:
            - ACCOUNT_SERVICE=http://account-service:8080
            - FRONTEND_SERVICE=http://frontend:5173
            - FILE_SERVICE=http://file-service:8080
            - DOCUMENT_SERVICE=http://document-service:8080
        networks:
            - nginx-net
        depends_on:
            - account-service
            - document-service
            - file-service

    # Account service
    accounts-sessions-db:
        image: bitnami/keydb:6.3.4
        environment:
            - KEYDB_DATABASE=state
            - KEYDB_PASSWORD=${SESSION_REDIS_PASSWORD}
        healthcheck:
            test: [ "CMD", "keydb-cli", "-a", "${SESSION_REDIS_PASSWORD}", "--raw", "incr", "ping" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - account-service-net

    accounts-db:
        image: postgres:17.2
        restart: always
        environment:
            - POSTGRES_DB=${ACCOUNT_DB_NAME}
            - POSTGRES_USER=${ACCOUNT_DB_USER}
            - POSTGRES_PASSWORD=${ACCOUNT_DB_PASSWORD}
        volumes:
            - accounts-db:/var/lib/postgresql/data
            - ./dev/db/accounts/init:/docker-entrypoint-initdb.d
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U admin" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - account-service-net

    account-service:
        build:
            context: ./services/account-service
            target: dev
        restart: always
        environment:
            - EDITMD_SESSION_COOKIE=${EDITMD_SESSION_COOKIE}
            - EDITMD_DOMAIN=${EDITMD_DOMAIN}
            - EDITMD_API_KEY=${EDITMD_API_KEY}

            - EDITMD_FRONTEND_HOST=http://frontend
            
            - SPRING_DATASOURCE_URL=jdbc:postgresql://accounts-db:5432/${ACCOUNT_DB_NAME}
            - SPRING_DATASOURCE_USERNAME=${ACCOUNT_DB_USER}
            - SPRING_DATASOURCE_PASSWORD=${ACCOUNT_DB_PASSWORD}

            - REDIS_HOST=accounts-sessions-db
            - REDIS_PORT=6379
            - REDIS_PASSWORD=${SESSION_REDIS_PASSWORD}

            - GITHUB_OAUTH_CLIENT_ID=${GITHUB_OAUTH_CLIENT_ID}
            - GITHUB_OAUTH_CLIENT_SECRET=${GITHUB_OAUTH_CLIENT_SECRET}
        depends_on:
            - accounts-db
            - accounts-sessions-db
        networks:
            - nginx-net
            - account-service-net
        develop:
            watch:
                - path: ./services/account-service/src  # Watch for changes in the source folder
                  action: sync  # Sync the changes
                  target: /app/src  # Sync to container's source directory
                - path: ./services/account-service/pom.xml  # Watch for changes in pom.xml
                  action: rebuild

    # Document service
    document-service:
        build:
            context: ./services/document-service
            target: dev
        restart: always
        environment:
            - EDITMD_SESSION_COOKIE=${EDITMD_SESSION_COOKIE}
            - EDITMD_DOMAIN=${EDITMD_DOMAIN}
            - EDITMD_API_KEY=${EDITMD_API_KEY}

            - EDITMD_FRONTEND_HOST=http://frontend
            - EDITMD_ACCOUNT_SERVICE_HOST=http://account-service:8080

            - REDIS_HOST=document-live-redis
            - REDIS_PORT=6379
            - REDIS_PASSWORD=${LIVE_REDIS_PASSWORD}

            - SPRING_DATASOURCE_URL=jdbc:postgresql://documents-db:5432/${DOCUMENT_DB_NAME}
            - SPRING_DATASOURCE_USERNAME=${DOCUMENT_DB_USER}
            - SPRING_DATASOURCE_PASSWORD=${DOCUMENT_DB_PASSWORD}
        depends_on:
            - account-service
            - documents-db
        networks:
            - nginx-net
            - document-service-net
        develop:
            watch:
                - path: ./services/document-service/src  # Watch for changes in the source folder
                  action: sync  # Sync the changes
                  target: /app/src  # Sync to container's source directory
                - path: ./services/document-service/pom.xml  # Watch for changes in pom.xml
                  action: rebuild

    documents-db:
        image: postgres:17.2
        restart: always
        environment:
            - POSTGRES_DB=${DOCUMENT_DB_NAME}
            - POSTGRES_USER=${DOCUMENT_DB_USER}
            - POSTGRES_PASSWORD=${DOCUMENT_DB_PASSWORD}
        volumes:
            - document-db:/var/lib/postgresql/data
            - ./dev/db/documents/init:/docker-entrypoint-initdb.d
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U admin" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - document-service-net

    document-live-redis:
        image: bitnami/keydb:6.3.4
        environment:
            - KEYDB_DATABASE=live
            - KEYDB_PASSWORD=${LIVE_REDIS_PASSWORD}
        healthcheck:
            test: [ "CMD", "keydb-cli", "-a", "${LIVE_REDIS_PASSWORD}", "--raw", "incr", "ping" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - document-service-net
            
    # File service
    file-service:
        build:
            context: ./services/file-service
            target: dev
        restart: always
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://file-db:5432/${FILE_DB_NAME}
            - SPRING_DATASOURCE_USERNAME=${FILE_DB_USER}
            - SPRING_DATASOURCE_PASSWORD=${FILE_DB_PASSWORD}
            - MINIO_PUBLIC_URL=${MINIO_PUBLIC_URL}
            - MINIO_INTERNAL_URL=${MINIO_INTERNAL_URL}
            - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
            - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
            - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
            - EDITMD_SESSION_COOKIE=${EDITMD_SESSION_COOKIE}
            - EDITMD_DOMAIN=${EDITMD_DOMAIN}
            - EDITMD_API_KEY=${EDITMD_API_KEY}
            - EDITMD_DOCUMENT_SERVICE_HOST=http://document-service:8080
            - EDITMD_ACCOUNT_SERVICE_HOST=http://account-service:8080
        depends_on:
            - minio
            - file-db
        networks:
            - nginx-net
            - file-service-net
        develop:
            watch:
                - path: ./services/file-service/src  # Watch for changes in the source folder
                  action: sync  # Sync the changes
                  target: /app/src  # Sync to container's source directory
                - path: ./services/file-service/pom.xml  # Watch for changes in pom.xml
                  action: rebuild

    file-db:
        image: postgres:17.2
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=${FILE_DB_NAME}
            - POSTGRES_USER=${FILE_DB_USER}
            - POSTGRES_PASSWORD=${FILE_DB_PASSWORD}
        volumes:
            - file-db:/var/lib/postgresql/data
            - ./dev/db/files/init:/docker-entrypoint-initdb.d
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${FILE_DB_USER}" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - file-service-net

    minio:
        image: quay.io/minio/minio
        container_name: minio
        ports:
            - "9000:9000"
            - "9090:9090"
        volumes:
            - minio-data:/data
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
        command:
            server /data --console-address ":9090"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live" ]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            - file-service-net
    
    # Frontend service
    frontend:
        build:
            context: ./services/frontend
            target: dev
        environment:
            - EDITMD_SESSION_COOKIE=${EDITMD_SESSION_COOKIE}
            - PUBLIC_EDITMD_DOMAIN=${EDITMD_DOMAIN}
            - EDITMD_DOMAIN=${EDITMD_DOMAIN}
            - EDITMD_API_KEY=${EDITMD_API_KEY}
            - EDITMD_ACCOUNT_SERVICE_HOST=http://account-service:8080
            - EDITMD_DOCUMENT_SERVICE_HOST=http://document-service:8080
            - EDITMD_FILE_SERVICE_HOST=http://file-service:8080
        develop:
            watch:
                - path: ./services/frontend/src
                  action: sync
                  target: /app/src
                - path: ./services/frontend/static
                  action: sync
                  target: /app/static
                - path: ./services/frontend/package.json
                  action: rebuild
        volumes:
            - ./services/frontend/.svelte-kit:/app/.svelte-kit
        networks:
            - nginx-net

volumes:
    accounts-db:
    document-db:
    file-db:
    minio-data:

networks:
    nginx-net:
        driver: bridge
    account-service-net:
        driver: bridge
    document-service-net:
        driver: bridge
    file-service-net:
        driver: bridge
