apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-document-service
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-document-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-document-service
    spec:
      containers:
      - name: document-service
        image: "{{ .Values.documentService.image.repository }}:{{ .Values.documentService.image.tag }}"
        imagePullPolicy: Always
        env:
        - name: SPRING_DATASOURCE_URL
          value: {{ if .Values.documentsDb.enabled }}jdbc:postgresql://{{ .Release.Name }}-documents-db:5432/{{ .Values.documentsDb.dbName }}{{ else }}jdbc:postgresql://{{ .Values.documentsDb.external.host }}:{{ .Values.documentsDb.external.port }}/{{ .Values.documentsDb.dbName }}{{ end }}
        - name: SPRING_DATASOURCE_USERNAME
          value: {{ .Values.documentsDb.user }}
        - name: SPRING_DATASOURCE_PASSWORD
          value: {{ .Values.documentsDb.password }}
        - name: EDITMD_ACCOUNT_SERVICE_HOST
          value: http://{{ .Release.Name }}-account-service:8080
        - name: EDITMD_SESSION_COOKIE
          value: {{ .Values.global.sessionCookie.name }}
        - name: EDITMD_DOMAIN
          value: https://{{ .Values.global.domain }}
        - name: EDITMD_API_KEY
          value: {{ .Values.global.apiKey }}
        - name: REDIS_HOST
          value: {{ if .Values.documentsLiveDb.enabled }}{{ .Release.Name }}-documents-live-db{{ else }}{{ .Values.documentsLiveDb.external.host }}{{ end }}
        - name: REDIS_PORT
          value: "{{ if .Values.documentsLiveDb.enabled }}6379{{ else }}{{ .Values.documentsLiveDb.external.port }}{{ end }}"
        - name: REDIS_PASSWORD
          value: {{ .Values.documentsLiveDb.password }}
        livenessProbe:
          httpGet:
            path: /api/documents/actuator/health/liveness
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /api/documents/actuator/health/readiness
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          {{- toYaml .Values.documentService.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-document-service
spec:
  ports:
  - port: 8080
  selector:
    app: {{ .Release.Name }}-document-service
---
{{- if .Values.documentService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-document-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-document-service
  minReplicas: {{ .Values.documentService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.documentService.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
{{- end }}