{{- if .Values.documentsLiveDb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-documents-live-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-documents-live-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-documents-live-db
    spec:
      containers:
      - name: documents-live-db
        image: "{{ .Values.documentsLiveDb.image }}"
        env:
          - name: KEYDB_DATABASE
            value: {{ .Values.documentsLiveDb.dbName }}
          - name: KEYDB_PASSWORD
            value: {{ .Values.documentsLiveDb.password }}
        ports:
          - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-documents-live-db
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-documents-live-db
{{- end }}