{{- if .Values.ingress.traefik.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-https-redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-traefik-ingressroute
spec:
  entryPoints:
    - {{ .Values.ingress.traefik.entryPoints.websecure }}
    - {{ .Values.ingress.traefik.entryPoints.web }}
  routes:
  - match: Host(`{{ .Values.global.domain }}`) && PathPrefix(`/`)
    kind: Rule
    entryPoints:
      - {{ .Values.ingress.traefik.entryPoints.web }}
    middlewares:
      - name: {{ .Release.Name }}-https-redirect
    services: []
  - match: Host(`{{ .Values.global.domain }}`) && PathPrefix(`/api/accounts`, `/api/accounts/`)
    kind: Rule
    entryPoints:
      - {{ .Values.ingress.traefik.entryPoints.websecure }}
    services:
      - name: {{ .Release.Name }}-account-service
        port: 8080
  - match: Host(`{{ .Values.global.domain }}`) && PathPrefix(`/api/documents`, `/api/documents/`)
    kind: Rule
    entryPoints:
      - {{ .Values.ingress.traefik.entryPoints.websecure }}
    services:
      - name: {{ .Release.Name }}-document-service
        port: 8080
  - match: Host(`{{ .Values.global.domain }}`) && PathPrefix(`/api/files`, `/api/files/`)
    kind: Rule
    entryPoints:
      - {{ .Values.ingress.traefik.entryPoints.websecure }}
    services:
      - name: {{ .Release.Name }}-file-service
        port: 8080
  - match: Host(`{{ .Values.global.domain }}`) && PathPrefix(`/`)
    kind: Rule
    entryPoints:
      - {{ .Values.ingress.traefik.entryPoints.websecure }}
    services:
      - name: {{ .Release.Name }}-frontend
        port: 3000
  tls:
    secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}