CREATE TABLE files (
    Id UUID PRIMARY KEY,
    DocumentId UUID NOT NULL,
    Path TEXT NOT NULL,
    Type VARCHAR(50) NOT NULL,
    CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_document_id ON files USING BTREE (DocumentId);
