name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get short commit hash
        id: commit
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push document-service
        uses: docker/build-push-action@v6
        with:
          context: ./services/document-service
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/document-service:latest
            ghcr.io/${{ github.repository }}/document-service:${{ env.COMMIT_HASH }}

      - name: Build and push account-service
        uses: docker/build-push-action@v6
        with:
          context: ./services/account-service
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/account-service:latest
            ghcr.io/${{ github.repository }}/account-service:${{ env.COMMIT_HASH }}

      - name: Build and push file-service
        uses: docker/build-push-action@v6
        with:
          context: ./services/file-service
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/file-service:latest
            ghcr.io/${{ github.repository }}/file-service:${{ env.COMMIT_HASH }}

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./services/frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/frontend:latest
            ghcr.io/${{ github.repository }}/frontend:${{ env.COMMIT_HASH }}