name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Get commit hash
      id: commit
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV
        echo "::set-output name=commit_hash::${COMMIT_HASH}"

    - name: Build account-service image
      working-directory: ./services/account-service
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/account-service:latest -t ghcr.io/${{ github.repository_owner }}/account-service:${{ steps.commit.outputs.commit_hash }} .

    - name: Build document-service image
      working-directory: ./services/document-service
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/document-service:latest -t ghcr.io/${{ github.repository_owner }}/document-service:${{ steps.commit.outputs.commit_hash }} .

    - name: Build file-service image
      working-directory: ./services/file-service
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/file-service:latest -t ghcr.io/${{ github.repository_owner }}/file-service:${{ steps.commit.outputs.commit_hash }} .

    - name: Build frontend image
      working-directory: ./services/frontend
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/frontend:latest -t ghcr.io/${{ github.repository_owner }}/frontend:${{ steps.commit.outputs.commit_hash }} .

    outputs:
      commit_hash: ${{ steps.commit.outputs.commit_hash }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish account-service image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/account-service:latest
        docker push ghcr.io/${{ github.repository_owner }}/account-service:${{ needs.build.outputs.commit_hash }}

    - name: Publish document-service image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/document-service:latest
        docker push ghcr.io/${{ github.repository_owner }}/document-service:${{ needs.build.outputs.commit_hash }}

    - name: Publish file-service image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/file-service:latest
        docker push ghcr.io/${{ github.repository_owner }}/file-service:${{ needs.build.outputs.commit_hash }}

    - name: Publish frontend image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/frontend:latest
        docker push ghcr.io/${{ github.repository_owner }}/frontend:${{ needs.build.outputs.commit_hash }}
