name: Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get commit hash
      id: commit
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and push account-service image
      working-directory: ./services/account-service
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/account-service:latest -t ghcr.io/${{ github.repository_owner }}/account-service:${{ env.COMMIT_HASH }} .
        docker push ghcr.io/${{ github.repository_owner }}/account-service:latest
        docker push ghcr.io/${{ github.repository_owner }}/account-service:${{ env.COMMIT_HASH }}

    - name: Build and push document-service image
      working-directory: ./services/document-service
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/document-service:latest -t ghcr.io/${{ github.repository_owner }}/document-service:${{ env.COMMIT_HASH }} .
        docker push ghcr.io/${{ github.repository_owner }}/document-service:latest
        docker push ghcr.io/${{ github.repository_owner }}/document-service:${{ env.COMMIT_HASH }}

    - name: Build and push file-service image
      working-directory: ./services/file-service
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/file-service:latest -t ghcr.io/${{ github.repository_owner }}/file-service:${{ env.COMMIT_HASH }} .
        docker push ghcr.io/${{ github.repository_owner }}/file-service:latest
        docker push ghcr.io/${{ github.repository_owner }}/file-service:${{ env.COMMIT_HASH }}

    - name: Build and push frontend image
      working-directory: ./services/frontend
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/frontend:latest -t ghcr.io/${{ github.repository_owner }}/frontend:${{ env.COMMIT_HASH }} .
        docker push ghcr.io/${{ github.repository_owner }}/frontend:latest
        docker push ghcr.io/${{ github.repository_owner }}/frontend:${{ env.COMMIT_HASH }}
